### ISSUE TITLE
Continue from MPI-based metaD runs

### ISSUE THREAD

**Issue by xiki-tempula** [plumed/plumed2#726] opened 2021-08-03 20:25 UTC
Related to #624.

Say I have a metaD run where I have 8 walkers in 8 folders 0 1 2 3 4 5 6 7 
They will all be using the same plumed file.

```
protein1: CENTER ATOMS=31,89,167,252,322,392,472
protein2: CENTER ATOMS=550,608,686,771,841,911,991
Protein: CENTER ATOMS=protein1,protein2
e2e: XYDISTANCES ATOMS1=protein1,1043 ATOMS2=protein2,1043 LOWEST
e2ec: DISTANCE ATOMS=Protein,1043 COMPONENTS

UPPER_WALLS ARG=e2e.lowest AT=4.0 KAPPA=10000.0 LABEL=uwall
UPPER_WALLS ARG=e2ec.z AT=0.5 KAPPA=10000.0 LABEL=zwall

metad: METAD ARG=e2ec.x,e2ec.y ...
# Deposit a Gaussian every 500 time steps, with initial height equal to 1.2 kJ/mol
  PACE=500 HEIGHT=1
# the bias factor should be wisely chosen
  BIASFACTOR=8
# Gaussian width (sigma) should be chosen based on CV fluctuation in unbiased run
  SIGMA=0.2,0.2
# Gaussians will be written to file and also stored on grid
  GRID_MIN=-6.5,-5.5 GRID_MAX=6.5,5.5
  WALKERS_MPI FILE=../HILLS
...

PRINT STRIDE=2500 ARG=e2e.lowest,e2ec.x,e2ec.y,e2ec.z FILE=COLVAR
```

However, it seems that If I were to continue the run with the command `mpirun -np 8 mdrun_mpi -deffnm prod -plumed ../plumed.dat -multidir 0 1 2 3 4 5 6 7 -ntomp 5 -cpi -maxh 23.5`, I got 

```
Unknown exception:
(exception type: N4PLMD14ExceptionErrorE)

+++ PLUMED error
+++ at IFile.cpp:98, function PLMD::IFile& PLMD::IFile::advanceField()
+++ message follows +++
file ../HILLS: mismatch between number of fields in file and expected number
```

**Comment by invemichele** [comment] 2021-08-04 07:45
Did you check if the last line of the HILLS file is fine? Depending on how the simulation ended the last line of the HILLS file might be truncated, thus with fewer fields

**Comment by xiki-tempula** [comment] 2021-08-04 08:27
@invemichele Thanks for the reply. I have checked and they are fine. In fact, all of my simulations cannot restart due to this error.

**Comment by invemichele** [comment] 2021-08-04 11:55
The error says that one of the lines of the HILLS file has the wrong number of columns, so I would check if this is true. 
For example, if you run `awk 'NR>7{if(a!=NF) print NR,NF;a=NF;}' HILLS` do you get something different from `8 7` as output?
Hopefully it's just a one-time problem of this particular HILLS file :)

If instead the HILLS file is ok, then there is some subtle issue and I guess more details are needed to fix it. The best thing would be to share a minimal setup so others can reproduce the bug.

**Comment by xiki-tempula** [comment] 2021-08-06 17:06
@invemichele I tried to create a minimum input file but I cannot get the problem reproduced, where restart the simulation would run normally.

I used the command `awk 'NR>7{if(a!=NF) print NR,NF;a=NF;}' HILLS` to identify the line with a problem and removing the problematic line seems to solve the issue.

However, it seems a little bizzar to me that the error seems to occur in the middle of the file.

```
      450869.9899222702      2.021120820726718      2.792388285909346                    0.2                    0.2     0.0165716368056181                      8
      450869.9899222702     -1.073487349918945     -1.981984853744609                    0.2                    0.2    0.01670183984161323                      8
      450869.9899222702      0.355861152921368      2.817118218966923                    0.2#! FIELDS time e2ec.x e2ec.y sigma_e2ec.x sigma_e2ec.y height biasf
#! SET multivariate false
#! SET kerneltype gaussian
      425849.9904815108     -2.529825040272219      3.483460937227512                    0.2                    0.2    0.01322293804293742                      8
      425849.9904815108     -2.278369358607681     -3.648510404995591                    0.2                    0.2     0.0132886191253996                      8
      425849.9904815108     -1.299881798880495      3.810957329613876                    0.2                    0.2    0.01136020786434862                      8

```

**Comment by GiovanniBussi** [comment] 2021-08-13 13:26
Hi!

Related to this point:

>However, it seems a little bizarre to me that the error seems to occur in the middle of the file.

It seems like at the second to the last successful restart the last line was something like this *without* an end of line:
```
      450869.9899222702      0.355861152921368      2.817118218966923                    0.2
```
Upon restart, the file is appended, resulting in line like this:
```
      450869.9899222702      0.355861152921368      2.817118218966923                    0.2#! FIELDS time e2ec.x e2ec.y sigma_e2ec.x sigma_e2ec.y height biasf
```
that triggers the error at the next restart.

I am not sure how to fix this. Perhaps we can force that when a file with fields is appended there is a newline added if not present already. Or even append it *anyway* (it should be harmless). Notice that not giving error when the EOL is missing is a consequence of #126 

Related to this point:

> I suspect that using the -maxh command from gromacs to end the simulation will not give a clean exit of plumed?

I traditionally found problems with maxh and multiple replicas, that I thought were due to replicas being blocked at different time resulting in a non-clean exit, but I am not sure this is the case here. You might check the log files (of the second-to-last successful run).

**Comment by invemichele** [comment] 2021-08-13 14:41
An easy thing to do that might be helpful is to make the error more clear for the users, for instance printing the linenumber of the faulty line, or even the whole line. The latter can be done e.g. by changing [this line](https://github.com/plumed/plumed2/blob/master/src/tools/IFile.cpp#L98) in the following way: 
`plumed_merror("file " + getPath() + ": mismatch between number of fields in file and expected number\n  this is the faulty line:\n"+line);`
Then the error message becomes:
```
+++ message follows +++
file ../HILLS: mismatch between number of fields in file and expected number
  this is the faulty line:
      450869.9899222702      0.355861152921368      2.817118218966923                    0.2
```
which hopefully makes it easier to fix the HILLS file...

**Comment by xiki-tempula** [comment] 2021-08-13 15:53
I think this is a good idea

**Comment by GiovanniBussi** [comment] 2021-08-14 14:05
@xiki-tempula I added the message suggested by @invemichele 

However, I thought better about it and I think it is not a good idea to add a newline if it's missing. Let's say that your last line should be
```
10 20 30
```
and is truncated to
```
10 20 3+nonewline
```
there would be no way to detect the error.

I thus close this issue, please feel free to reopen it if you have other suggestions. Thanks!

**Comment by GiovanniBussi** [comment] 2021-08-14 14:09
Mm, actually even now there's no way to detect such an error. Maybe the only solution is to allow no-new-line termination only on plumed input files and disable it on files with FIELDS. I will think about it.

**Comment by GiovanniBussi** [comment] 2021-08-14 15:17
OK I found the problem.

Currently, a non-terminated last line is only allowed for `plumed.dat` files. For all other files, if the last line is not terminated *it is ignored*. I think this is not correct. Indeed, for all other files, if the last line is not terminated *it should report an error*.

I will add this. This would allow to see the failure at the first incorrect restart and not at the second.

**Closed** 2021-08-15 13:02 UTC
