### ISSUE TITLE
Issue with integrate_grid and openMP

### ISSUE THREAD

**Issue by carlocamilloni** [plumed/plumed2#417] opened 2018-12-07 09:59 UTC
@gtribello 
I think that decreasing the threshold for using openMP thread has highlighted a possible issue (threadsafety?) with integrate_grid (from plumed 2.4 on) all the regtests in plumed 2.3 go well

**Comment by GiovanniBussi** [comment] 2018-12-07 11:13
@carlocamilloni @gtribello maybe the problem is here:

https://github.com/plumed/plumed2/blob/b354ef881a7ce5dd8c8dbb0664c24bc45cd18c10/src/vesselbase/ActionWithVessel.cpp#L344

Notice that bvals is shared among threads.

A change that seems to fix the problem on my workstation (at least with a basic compilation without MPI) seems to be the replacement of this line:
https://github.com/plumed/plumed2/blob/b354ef881a7ce5dd8c8dbb0664c24bc45cd18c10/src/vesselbase/ActionWithVessel.cpp#L268
with this:
````
  if( nt*stride*2>nactive_tasks || !threadSafe() || !actionIsBridged) nt=1;
````

**Comment by carlocamilloni** [comment] 2018-12-07 18:39
Great! Sorry in Milan is holiday today, I’ll check it  the next days

**Comment by carlocamilloni** [comment] 2018-12-08 13:38
While @GiovanniBussi fix works, it removes the openmp parallelisation from a number of multicolvar that are likely safe (secondary structure and alphabeta among the one I use) so the solution is likely too conservative, @gtribello we need you :-)

**Comment by GiovanniBussi** [comment] 2018-12-08 16:01
Too bad... looking at the code again my fix does not make sense since bvals is a local variable. I just disabled the parallelization. So the problem is hidden somewhere else

**Comment by carlocamilloni** [comment] 2018-12-08 16:03
Unfortunately yes, 
I see differences in the derivatives stored in the histograms
It may be that using histograms to analyse multicolvar make them thread unsafe

**Comment by GiovanniBussi** [comment] 2018-12-08 16:12
Maybe the problem is ‘der_list’. I see it is not const

**Comment by gtribello** [comment] 2018-12-08 17:51
Hello @carlocamilloni and @GiovanniBussi 

Sorry for taking my time getting to this.  Can you please tell me how to recover the error.  i.e. what branch should I be looking at and what test are you doing?  It is not very clear from the discussion above.

**Comment by gtribello** [comment] 2018-12-08 17:53
I think I know how to fix this but I am not sure where I should be fixing.

**Comment by carlocamilloni** [comment] 2018-12-08 17:55
Hi

I reverted the previous fix so you should apply the fix to v2.4 branch

C

**Comment by carlocamilloni** [comment] 2018-12-08 19:02
@gtribello 
You need to export PLUMED_NUM_THREADS=2 or more and have plumed compiled with openmp

**Comment by gtribello** [comment] 2018-12-08 19:52
Thanks @carlocamilloni 

It should be fixed now

**Closed** 2018-12-08 19:52 UTC

**Comment by carlocamilloni** [comment] 2018-12-08 20:59
Great
