### ISSUE TITLE
action centos 7 fails due to old python 3 

### ISSUE THREAD

**Issue by carlocamilloni** [plumed/plumed2#656] opened 2020-12-04 09:41 UTC
to compile MDAnalysis at least python 3.7 is needed, shall we abandon centos7 for centos8? or just test a minimal version of plumed there.

**Comment by GiovanniBussi** [comment] 2020-12-04 09:49
I would prefer to leave centos7 to test older gcc... I am afraid the problem is numpy. Maybe installing numpy 1.19 first fixes the problem? I will try right now.

**Comment by GiovanniBussi** [comment] 2020-12-04 10:21
Fixed in 00a1907030aab26ab46cdcda734ae71c99311c74

**Closed by GiovanniBussi** 2020-12-04 10:21 UTC
