### ISSUE TITLE
Wrong coordinates using getPositions() for first frame without MPI

### ISSUE THREAD

**Issue by divinours** [plumed/plumed2#442] opened 2019-02-11 17:27 UTC
`getPositions()` returns invalid values for the y coordinates of atoms at the first frame, when running on a single MPI node.
This was tested with gromacs 2016.4/plumed 2.4 and gromacs2018.4/plumed 2.5
### How to reproduce :
* Add the following lines to the start of the `calculate()` routine of any colvar:
```
static unsigned int nit = 0;
std::cout << "------ Frame   " << nit << std::endl;
const std::vector<Vector> &posref = getPositions();
for (std::vector<Vector>::const_iterator pit = posref.begin(); pit != posref.end(); ++pit)
    std::cout << (*pit)[0] << " " << (*pit)[1] << " " << (*pit)[2] << std::endl;
++nit;
```
* Running on one MPI node (using `mpirun -np 1 gmx_mpi mdrun` or `gmx_mpi mdrun`) gives (for example):
```
------ Frame   0
11.025 -0.35664 6.116
11.176 -0.60364 5.905
11.121 -0.944639 5.914
...
```
* Running on two or more MPI nodes gives:
```
------ Frame   0
11.025 12.57 6.116
11.176 12.323 5.905
11.121 11.982 5.914
...
```
* The following iterations look OK, but the error at iteration 0 impacts the coordinates at later timesteps when using one MPI node.

**Comment by GiovanniBussi** [comment] 2019-02-11 17:28
Can you check if the shift is equal to the box side?

**Comment by divinours** [comment] 2019-02-11 17:36
Yes, it looks like that indeed...

**Comment by GiovanniBussi** [comment] 2019-02-11 17:38
So it's not a bug. Gromacs probably stores those coordinates.

In any periodic system, CVs should be computed in such a way to be independent on which of the infinite equivalent periodic images is chosen for each atom. In case you want to know how much a particle moved, you need to apply PBCs on the distance from the initial coordinate.

I close this for now, feel free to reopen it if you think there are issues to solve.

Thanks!

**Closed by GiovanniBussi** 2019-02-11 17:38 UTC

**Comment by divinours** [comment] 2019-02-11 17:46
Thanks! Checking for PBC effects had completely slipped my mind, sorry!
