### ISSUE TITLE
Plumed 2.4.2 tests segfaulting/assertions failing with Intel 2018 and -O2 or above

### ISSUE THREAD

**Issue by heatherkellyucl** [plumed/plumed2#391] opened 2018-09-20 14:47 UTC
I've been trying to build plumed 2.4.2 with the Intel 2018 update 3 compiler and MPI. I was getting failed tests for a number of reasons, including segfaults. This is on RHEL 7.4 with underlying GCC 4.9.2.

Summary of the way the tests failed:

Major numerical diffs, not just last digit
`analysis/rt-uweights-integral`
`analysis/rt-weights-integral`
`basic/rt14`
`basic/rt24`
`basic/rt-fix-235`

Missing some lines of output - in four of them the last line wasn't written, and for `crystallization/rt-histogram` the output file had 40209 lines instead of 40611.
`analysis/rt0`
`analysis/rt-histo`
`basic/rt11c`
`crystallization/rt-histogram`
`multicolvar/rt-histogram`

Files not written at all
`analysis/rt-cube`

MPI bad termination
`basic/rt-mpi7b`
`basic/rt-mpi7`
`basic/rt-mpi9`

Segfaulted
`basic/rt12`
`basic/rt21`
`basic/rt-ttmetad1`

Aborted
`basic/rt-ttmetad0`
`basic/rt-ttmetad2`

Minor and expected numerical diffs - this one failed for us with 2.4.1 and Intel 2017 too, with exactly the same numbers, so isn't the problem here.
`isdb/rt-emmi`

It made no difference if I built with OpenBLAS or used MKL. Normal configuration line was:
```
./configure --prefix=$INSTALL_PREFIX CXX=mpicxx CC=mpicc FC=mpif90 LIBS="-mkl -lifcore -lmatheval -lfl" CXXFLAGS="-axSSE2,AVX -fp-model strict"
touch src/crystallization.on
```
We had previously found that a few other tests failed with 2.4.1 and Intel 2017 if we didn't specify `-fp-model strict`.

I tried reducing the optimisation level: at `-O1` the tests all succeed. At `-O2` they all fail as above. 

Setting `--enable-debug --enable-debug-glibcxx` with `-O2` still let the tests succeed (apart from `isdb/rt-emmi`) so the debug flags stopped whatever optimisation was causing it.

Configuring like below made the tests fail, not segfault, and gave me info about assertion failures:
```
./configure --prefix=$INSTALL_PREFIX CXX=mpicxx CC=mpicc FC=mpif90 LIBS="-mkl -lifcore -lmatheval -lfl" CXXFLAGS="-axSSE2,AVX -fp-model strict" --enable-debug
```
The results were:

`analysis/rt-weights-integral`, `analysis/rt-uweights-integral` and `crystallization/rt-wcsurface2/` have a failed assertion in GridVessel.h line 257.
```
Running regtest in /dev/shm/plumed-build.Lj4ltFDG/mkl-debug/plumed2-2.4.2/regtest/analysis/rt-weights-integral
++ Test type: driver
++ Arguments: --plumed plumed.dat --ixyz trajectory.xyz --dump-forces forces --dump-forces-fmt %8.4f
++ Processors: 0
/dev/shm/plumed-build.Lj4ltFDG/mkl-debug/plumed2-2.4.2/regtest/analysis/rt-weights-integral/tmp
../../scripts/run: line 129: 27956 Aborted                 $mpi $valgrind $plumed driver $arg > out 2> err
FAILURE: exit code 134
terminate called after throwing an instance of 'PLMD::Exception'
  what():  
+++ Internal PLUMED error
+++ file GridVessel.h, line 257
+++ message: assertion failed ip<npoints
FAILURE
```

`basic/rt-mpi7b`, `basic/rt-mpi9` have a failed assertion in Grid.cpp, line 418 and `basic/rt-mpi7`, `basic/rt-ttmetad1`, `basic/rt12`, `basic/rt-ttmetad2`, `basic/rt-ttmetad0` have the same failure in line 491.
```
Running regtest in /dev/shm/plumed-build.Lj4ltFDG/mkl-debug/plumed2-2.4.2/regtest/basic/rt-mpi7
++ Test type: driver
++ Arguments: --plumed=plumed.dat --timestep=0.05 --ixyz trajectory.xyz --multi 3
++ Processors: 3
/dev/shm/plumed-build.Lj4ltFDG/mkl-debug/plumed2-2.4.2/regtest/basic/rt-mpi7/tmp
FAILURE: exit code 6
terminate called after throwing an instance of 'PLMD::Exception'
  what():
+++ Internal PLUMED error
+++ file Grid.cpp, line 491
+++ message: assertion failed index<maxsize_ && usederiv_ && der.size()==dimension_
terminate called after throwing an instance of 'PLMD::Exception'
  what():
+++ Internal PLUMED error
+++ file Grid.cpp, line 491
+++ message: assertion failed index<maxsize_ && usederiv_ && der.size()==dimension_terminate called after th
rowing an instance of 'PLMD::Exception'
  what():
+++ Internal PLUMED error
+++ file Grid.cpp, line 491
+++ message: assertion failed index<maxsize_ && usederiv_ && der.size()==dimension_

FAILURE
```

`basic/rt21` has a failed assertion in Grid.cpp line 236.
```
Running regtest in /dev/shm/plumed-build.Lj4ltFDG/mkl-debug/plumed2-2.4.2/regtest/basic/rt21
++ Test type: driver
++ Arguments: --plumed plumed.dat --ixyz traj.xyz
++ Processors: 0
/dev/shm/plumed-build.Lj4ltFDG/mkl-debug/plumed2-2.4.2/regtest/basic/rt21/tmp
../../scripts/run: line 129:  5514 Aborted                 $mpi $valgrind $plumed driver $arg > out 2> err
FAILURE: exit code 134
terminate called after throwing an instance of 'PLMD::Exception'
  what():  
+++ Internal PLUMED error
+++ file Grid.cpp, line 236
+++ message: assertion failed index<maxsize_
FAILURE
```

The only difference was that `basic/rt14/` did not fail this time (had numerical differences before) and was replaced by `crystallization/rt-wcsurface2/` which had the assertion failure. 

The tests that wrote no files or only write partial files did the same thing here.

(I have a whole load of output at https://github.com/UCL-RITS/rcps-buildscripts/issues/210 where I was trying to build it in order to use with dl_poly if you want to see - but I have tried to include everything relevant here).

I can attach make and test logs if you wish, and let me know if there's anything else you want me to try.

**Comment by GiovanniBussi** [comment] 2018-09-21 07:50
@heatherkellyucl thanks for the detailed report!

Most of the bugs are in out-of-grid access. I managed to reproduce the problem on my workstation and I think there is a serious bug in the intel compiler when using `-fp-model strict`.

The problem is in the following code in `tools/Grid.cpp`, line 112:

````
std::cerr<<"PRE "<<nbin_[0]<<" "<<pbc_[0]<<"\n";
  for(unsigned int i=0; i<dimension_; ++i) {
    dx_.push_back( (max_[i]-min_[i])/static_cast<double>( nbin_[i] ) );
    if( !pbc_[i] ) { max_[i] += dx_[i]; nbin_[i] += 1; }
    maxsize_*=nbin_[i];
  }
std::cerr<<"POST "<<maxsize_<<" "<<nbin_[0]<<"\n";
````
(I added the `std::cerr` lines)

In regtest `basic/rt21` you have `dimension_=1`, `pbc[0]=0`, and `nbin_[0]=100` before the loop. During the loop, since `pbc_[0]` is false, `nbin_[0]` is increased to 101. Notice that `maxsize_` is the product of all the `nbin_` elements **after they were increased** and in this case should be 101.

When I compiled Grid.cpp with `-fp-model strict` I get this:
````
PRE 100 0
POST 100 101
````
When I compiled without `-fp-model-strict` I get correctly this:
````
PRE 100 0
POST 101 101
````

I don't understand how the compiler can be fooled by such a simple loop. I would just remove the `-fp-model strict` option.

Notice that this will likely solve the problem with the missing final line in some files.

Can you check if this is solving also the other bugs?

Thanks a lot!

Giovanni

**Comment by heatherkellyucl** [comment] 2018-09-21 11:50
Interestingly, with `-fp-model precise` all tests pass, even `isdb/rt-emmi`.

**Comment by GiovanniBussi** [comment] 2018-09-21 13:08
@heatherkellyucl 

About reporting to INTEL: I tried to reproduce the error with a small program but I can't. I am afraid they won't be willing to compile plumed just to see the problem.

About fp-model precise: I think there are few tests that are a bit instable (numerically) and sensitive to optimization. However, I would not worry about it.

I will close the issue now, feel free to reopen it if you think the problem is not solved.

Thanks again for the report and for making an effort to install plumed correctly!

Giovanni

**Closed by GiovanniBussi** 2018-09-21 13:08 UTC

**Comment by heatherkellyucl** [comment] 2018-09-21 13:32
`strict` and `precise` giving different numerical results is fairly serious, so I'll report it to them.

**Comment by GiovanniBussi** [comment] 2018-09-21 13:34
@heatherkellyucl ok thanks. PLUMED is available of course and you can point them to those lines in case they are willing to reproduce it.
